apiVersion: v1
kind: Namespace
metadata:
  name: laravel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel
type: Opaque
data:
  DB_USERNAME: bGFyYXZlbA==
  DB_PASSWORD: bGFyYXZlbA== 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel
          image: buberistovska/blog:v16
          envFrom:
            - configMapRef:
                name: laravel-config
          ports:
            - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  namespace: laravel
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: bube.blog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laravel-service
                port:
                  number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: laravel
data:
  my.cnf: |
    [mysqld]
    max_connections=100
    innodb_buffer_pool_size=2G
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: laravel
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: laravel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: laravel
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: buberistovska/mysql:v16
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: dbdata
              mountPath: /var/lib/mysql
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: mysql-pvc


